version: "3.8"

services:
  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network

  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-network

  # Database Service
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
